version: "3.9"

services:
  streamlit:
    build: ./app
    container_name: streamlit_app
    ports:
      - "8501:8501"   # local access: http://localhost:8501
    volumes:
      - ./app:/app   # <--- THIS is the magic line
    environment:
      - STREAMLIT_SERVER_RUN_ON_SAVE=true

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_CLOUDFLARE}
    volumes:
      - ./cloudflared:/etc/cloudflared